---

- include: "facts.yml"
  tags: "always"

- include: "packages-xenial.yml"
  tags: "redis-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "16.04"

- include: "redis.yml"
  tags: "redis-redis"

- include: "optimize.yml"
  tags: "redis-optimize"
