---

- name: "check if /etc/yum.repos.d/epel.repo exists"
  stat:
    path: "/etc/yum.repos.d/epel.repo"
  changed_when: False
  register: epel_repo

- name: "install epel-bootstrap GPG key"
  when: not epel_repo.stat.exists
  copy:
    src: "RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}-BOOTSTRAP"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-BOOTSTRAP"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "import epel-bootstrap GPG key"
  when: not epel_repo.stat.exists
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-BOOTSTRAP"
    state: "present"

- name: "install epel-bootstrap repository"
  when: not epel_repo.stat.exists
  copy:
    src: "epel-{{ ansible_distribution_major_version }}-bootstrap.repo"
    dest: "/etc/yum.repos.d/epel-bootstrap.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "install EPEL repository"
  when: not epel_repo.stat.exists
  yum:
    enablerepo: "epel-bootstrap"
    name: "epel-release"
    state: "present"

- name: "remove epel-bootstrap repository"
  file:
    dest: "/etc/yum.repos.d/epel-bootstrap.repo"
    state: "absent"

- name: "remove epel-bootstrap key"
  file:
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-BOOTSTRAP"
    state: "absent"

