---

- name: "enable unbound"
  service:
    name: "unbound"
    enabled: True

- name: "start unbound"
  service:
    name: "unbound"
    state: "started"
  register: unbound_start

# This shouldn't be a handler so that we can test configuration changes.
- name: "restart unbound"
  when: >
    unbound_conf is defined
    and unbound_conf.changed
    and not unbound_start.changed
  service:
    name: "unbound"
    state: "restarted"

- name: "check DNSSEC resolution org."
  when: >
    ( unbound_conf is defined and unbound_conf.changed )
    or ( unbound_start.changed )
  command: "/usr/bin/dig @localhost org. SOA +dnssec +noall +comments"
  register: dig_org
  changed_when: False
  failed_when: "' ad' not in dig_org.stdout"

- name: "check DNSSEC resolution dnssec-failed.org"
  when: >
    ( unbound_conf is defined and unbound_conf.changed )
    or ( unbound_start.changed )
  command: "/usr/bin/dig @localhost +noall +comments dnssec-failed.org"
  register: dig_dnssec_failed
  changed_when: False
  failed_when: "'status: SERVFAIL' not in dig_dnssec_failed.stdout"
  ignore_errors: True

# Only amend resolv.conf after the previous tests have passed.
- name: "install /etc/resolv.conf"
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: "root"
    group: "root"
    mode: "0644"

