---
- include: "packages-xenial.yml"
  tags: "postfix-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "16.04"

- include: "configs.yml"
  tags: "postfix-configs"

- include: "services.yml"
  tags: "postfix-services"
