---

# COPY THIS FILE TO "group_vars/all/main.yml".

discourse_hostname:           "localhost"
discourse_developer_emails:   ["dev@dev.com"]

# See <docs/README.migrate-postgres.rst> for help on upgrading.
postgres_version:             "9.5"

# Generate a long, random password here.
postgres_password:            "password"

# If you have a dedicated postgres server, 25% of total RAM is a good starting
# point. If running postgres on the same server as everything else, try 12.5%.
#postgres_shared_buffers:      "128MB"

# If you only have 1GB RAM, use 2 workers. Otherwise increase to 3 or 4.
#discourse_unicorn_workers:    "2"

# If left as the default 'localhost', postfix and opendkim will be installed.
# Read <docs/README.mail.rst> for instructions.
discourse_smtp_address:       "localhost"
discourse_smtp_port:          "25"
discourse_smtp_username:      ""
discourse_smtp_password:      ""
discourse_smtp_auth:          "plain"
discourse_smtp_start_tls:     "true"

#-----------------------#
# Further configuration #
#-----------------------#

# In the "roles/" directory are a collection of roles. Each role has a
# "defaults/main.yml" file which contains the default variables. You can
# override any of the default variables by defining them below.

# By default, Discourse connects to the database on localhost.
# Point Discourse to the database server:
discourse_db_host:            ""
discourse_db_port:            "5432"

# By default, postgres only listens for connections on localhost.
# Tell postgres to listen on all interfaces:
postgres_listen:              ["*"]
postgres_port:                "5432"

# By default, only localhost is allowed to connect to the postgres.
# Tell postgres to allow connections from the Discourse server:
postgres_hosts_allow:         ["<ip>"]

#Configure sql dump file to initialize database
sql_dump: "<your_dump_here>"

#Set this to True if your sql dump has the same email for every user.
#By default, askbot.rb will not create users with identical email addresses.
#If set to True, update roles/db-config/tasks/main.yml line 136 for dev email. 
update_auth_user: False

