---

- include: "facts.yml"
  tags: "always"

- include: "packages-xenial.yml"
  tags: "nginx-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "16.04"

- include: "configs.yml"
  tags: "nginx-configs"

- include: "pki.yml"
  tags: "nginx-pki"
  when: tls_enabled

- include: "selinux.yml"
  tags: "nginx-selinux"
  when: ansible_selinux.status != "disabled"

- include: "services.yml"
  tags: "nginx-services"
