---

- include: "facts.yml"
  tags: "always"

- include: "user.yml"
  tags: "rbenv-user"

- include: "packages-xenial.yml"
  tags: "rbenv-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "16.04"

- include: "ruby.yml"
  tags: "rbenv-ruby"
